"use client";
import { useState } from "react";
import { FormFieldConfig } from "./field-definitions";
export function DynamicFormRenderer({ fields }: { fields: FormFieldConfig[] }) {
  const [values, setValues] = useState<Record<string, string>>({});
  function update(key: string, value: string) { setValues((prev) => ({ ...prev, [key]: value })); }
  function submit() { const missing = fields.filter((field) => field.required && !values[field.key]); if (missing.length) return alert(`請先填寫必填欄位：${missing.map((f) => f.label).join("、")}`); localStorage.setItem("bizflow-demo-form-response", JSON.stringify({ values, submittedAt: new Date().toISOString() })); alert("表單已送出 Demo。\n正式版會寫入 FormResponse，並觸發審核流程 / 通知 / 工作流程。"); setValues({}); }
  return (
    <form className="space-y-4">{fields.map((field) => <div key={field.id}><label className="mb-1 block text-sm font-medium">{field.label}{field.required && <span className="text-red-500"> *</span>}</label>{field.type === "textarea" && <textarea className="input min-h-24" placeholder={`請輸入${field.label}`} value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)} />}{["text", "email", "phone", "address"].includes(field.type) && <input className="input" placeholder={`請輸入${field.label}`} value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)} />}{["number", "money"].includes(field.type) && <input type="number" className="input" placeholder={`請輸入${field.label}`} value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)} />}{field.type === "date" && <input type="date" className="input" value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)} />}{field.type === "datetime" && <input type="datetime-local" className="input" value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)} />}{field.type === "select" && <select className="input" value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)}><option value="">請選擇</option>{(field.options ?? ["選項一", "選項二"]).map((option) => <option key={option}>{option}</option>)}</select>}{field.type === "gps" && <button type="button" className="w-full rounded-xl border border-dashed border-slate-300 p-3 text-left text-sm text-slate-500 hover:bg-slate-50" onClick={() => { const demoGps = "25.0330, 121.5654"; update(field.key, demoGps); alert(`已取得 Demo GPS：${demoGps}`); }}>{values[field.key] ? `已取得定位：${values[field.key]}` : "點我取得 GPS 定位 Demo"}</button>}{field.type === "signature" && <button type="button" className="flex h-28 w-full items-center justify-center rounded-xl border border-dashed border-slate-300 text-sm text-slate-500 hover:bg-slate-50" onClick={() => { update(field.key, "已簽名"); alert("Demo：已完成手寫簽名。正式版可接 Signature Pad。"); }}>{values[field.key] || "點我模擬手寫簽名"}</button>}{["image", "file"].includes(field.type) && <input type="file" className="input" accept={field.type === "image" ? "image/*" : undefined} onChange={(e) => update(field.key, e.target.files?.[0]?.name ?? "")} />}{field.type === "relation" && <select className="input" value={values[field.key] ?? ""} onChange={(e) => update(field.key, e.target.value)}><option value="">選擇關聯客戶 / 商品 / 員工</option><option>米朵電商</option><option>精華液 A01</option><option>王小明</option></select>}</div>)}<button type="button" className="btn-primary w-full" onClick={submit}>送出表單</button></form>
  );
}
